# Generated by Django 5.1.1 on 2024-09-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tercera_preentrega_mateo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=250)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tercera_preentrega_mateo.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
